apiVersion: v1
kind: Service
metadata:
  name: argo-prj1-service-tuc
spec:
  selector:
    app: argo-prj1-tuc
  type: NodePort
  ports:
    - name: tcp8080
      protocol: TCP
      port: 8080
      targetPort: 8080
    - name: tcp8082
      protocol: TCP
      port: 8082
      targetPort: 8082