apiVersion: v1
kind: Service
metadata:
  name: argo-prj1-service-tuc
spec:
  selector:
    app: argo-prj1-tuc
  type: NodePort
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
    - protocol: TCP
      port: 8081
      targetPort: 8081