apiVersion: batch/v1
kind: Job
metadata:
  generateName: argo-prj1-notification-
  annotations:
    argocd.argoproj.io/hook: PostSync
    argocd.argoproj.io/hook-delete-policy: HookSucceeded
spec:
  template:
    spec:
      containers:
      - name: argo-prj1-postsync-notification
        image: curlimages/curl
        command:
          - "curl"
          - "-X"
          - "POST"
          - "-H"
          - "'Content-Type: application/json'"
          - "--data"
          - "{\"app\": \"argo-prj1\", \"repo\": \"https://github.com/DennisD2/argo-prj1.git\", \"config-repo\": \"https://github.com/DennisD2/argo-prj1-config.git\", \"branch\": \"main\", \"reason\": \"postSyncSuccess\"}"
          - "http://192.168.178.44:8080/postSync"
      restartPolicy: Never
  backoffLimit: 2
