apiVersion: v1
kind: Service
metadata:
  name: argo-prj1-service-dev
spec:
  selector:
    app: argo-prj1-dev
  type: NodePort
  ports:
    - name: tcp-8080
      protocol: TCP
      port: 8080
      targetPort: 8080
    - name: tcp-8081
      protocol: TCP
      port: 8081
      targetPort: 8081