apiVersion: v1
kind: Service
metadata:
  name: argo-prj1-service-prod
spec:
  selector:
    app: argo-prj1-prod
  type: NodePort
  ports:
    - name: tcp8080
      protocol: TCP
      port: 8080
      targetPort: 8080
    - name: tcp8088
      protocol: TCP
      port: 8088
      targetPort: 8088
